services:
  app:
    container_name: app
    depends_on:
      - mysql
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
      args:
        CONTAINER_USER: ${CONTAINER_USER:-appuser}
        CONTAINER_GID: ${CONTAINER_GID:-1000}
        CONTAINER_UID: ${CONTAINER_UID:-1000}
    tty: true
    environment:
      APP_ENV: local
      PROJECT_ID: ${GCP_PROJECT_ID:-example}
      FIREBASE_AUTH_EMULATOR_HOST: firebase:9099
    volumes:
      - ./src:/app
      - ./data/app:/usr/local/lib/python3.12/site-psackages
    ports:
      - 8880:8000
  mysql:
    container_name: mysql
    image: mysql:8.0.41
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
      MYSQL_USER: fastapi
      MYSQL_PASSWORD: fastapi
    volumes:
      - ./data/mysql:/var/lib/mysql
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOSTS=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - 8881:80
  firebase:
    container_name: firebase
    build:
      context: .
      dockerfile: ./docker/firebase/Dockerfile
    tty: true
    environment:
      PROJECT_ID: ${GCP_PROJECT_ID:-example}
      FIREBASE_AUTH_EMULATOR_HOST: firebase:9099
    volumes:
      - ./docker/firebase/firebase.json:/opt/firebase/firebase.json
      - ./docker/firebase/firebase.indexes.json:/opt/firebase/firebase.indexes.json
      - ./docker/firebase/firebaserc:/opt/firebase/.firebaserc
      - ./data/firebase/.config:/home/cloudsdk/.config
      - ./data/firebase/.cache:/home/cloudsdk/.cache
      - ./data/firebase/exports:/opt/firebase/exports
    ports:
      - 9099:9099
      - 14000:4000
    command: |
      firebase emulators:start  --import=./exports/data&& \
      sudo crond -l 1 -f